### ISSUE TITLE
Несколько виджетов на странице

### ISSUE THREAD

**Issue by developer-av** [yii2mod/yii2-markdown#1]
При использовании на одной странице нескольких виджетов не работает как ожидается

**Comment by ihorchepurnyi** [comment]
Объясните пожалуйста детальнее в чем проблема + покажите пожалуйста ваш код.

**Comment by developer-av** [comment]
Спасибо за быстрый ответ
```
<?php
    echo $form->field($model,
        'description_1')->widget(\yii2mod\markdown\MarkdownEditor::class, [
        'name' => 'description_1',
    ]);

    echo $form->field($model,
        'description_2')->widget(\yii2mod\markdown\MarkdownEditor::class, [
        'name' => 'description_2',
    ]);
?>
```

```
($model->description_1 === 'test 1') === true
($model->description_2 === 'test 2') === true
```

![image](https://user-images.githubusercontent.com/15675868/33215974-8a36ad38-d13a-11e7-9d41-45a64bbebad6.png)

**Comment by ihorchepurnyi** [comment]
окей, спасибо, гляну.

**Comment by ihorchepurnyi** [comment]
Исправил, обновите пожалуйста ваш пакет.

**Comment by developer-av** [comment]
Спасибо большое за оперативный фикс, всё работает

**Comment by ihorchepurnyi** [comment]
И вам большое спасибо!
