### ISSUE TITLE
Bootstrap tab bug

### ISSUE THREAD

**Issue by developer-av** [yii2mod/yii2-markdown#2]
Если виджет в неактивной табе
при переключения вместо текста просто белое поле
![image](https://user-images.githubusercontent.com/15675868/33987655-4f608c52-e0ca-11e7-891f-df12c4585a94.png)
После фокуса на поле всё норм

**Comment by ihorchepurnyi** [comment]
Здравствуйте, такую ошибку не видел. Возможно проблема с самим плагином, так как виджет по сути просто рендерит js из стороннего пакета.

**Comment by developer-av** [comment]
Добрый день, заработался и не туда написал..
Вы правы, это не проблема виджета.
Сейчас постучу по адресу
Прошу прощения за потраченное время

**Comment by ihorchepurnyi** [comment]
Рад помочь!
